http:
  routers:
    cloud-router:
      entryPoint: websecure
      service: cloud-service
      rule: Host(`cloud.davydehaas.dev`)

  services:
    cloud-service:
      loadBalancer:
        servers:
          - url: http://jotunheim_0:6443
